#!/usr/bin/env /usr/bin/zsh


MY_DATE=$(date +%Y%m%d_%H%M%S)
MY_LOGFILE="/storage/logs/runawayClock/$MY_DATE.RC.txt"

if [[ "$1" == "-p" ]]
then
  python -m runawayClock |& tee -a "$MY_LOGFILE"
else
  ~/.local/bin/runawayClock.bin
fi



#
